# .github/workflows/bot.yml
name: Daily posting to Slack
on:
    workflow_dispatch:
    schedule:
        # daily job
        - cron: '00 11 * * 1-5' 

jobs:
  bot_job:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          
        - name: Update apt cache
          run: sudo apt-get update
   
        - name: Install cURL Headers
          run: sudo apt-get install libcurl4-openssl-dev
    
        - name: Setup R
          uses: r-lib/actions/setup-r@v2
          with:
              r-version: '4.3'
        
        # This should install dependencies from the DESCRIPTION. Caching them too.  
        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
              cache-version: 2
        
        #- name: Install dependencies
        #  run: | 
        #       install.packages(c('httr', 'jsonlite', 'purrr', 'dplyr', 'readr', 
        #       'stringr', 'rlist', 'slackr', 'stringdist','googledrive','base64enc'))
        #  shell: Rscript {0}  

        - name: posting bot
          run: Rscript bot.R ${{secrets.CREDENTIALS}} ${{secrets.STATEFILE_GDRIVE}} ${{secrets.SLACK_BOT_TOKEN}} ${{secrets.F1000AUTH}}
        
    
