# .github/workflows/main.yml
name: Main
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          
        - name: Update apt cache
          run: sudo apt-get update
   
        - name: Install cURL Headers
          run: sudo apt-get install libcurl4-openssl-dev
    
        - name: Setup R
          uses: r-lib/actions/setup-r@v2
          with:
              r-version: '4.3'
        
        - name: Install dependencies
          run: | 
               install.packages(c('httr', 'jsonlite', 'purrr', 'dplyr', 'readr', 
               'stringr', 'rlist', 'slackr', 'stringdist','googledrive','base64enc'))
          shell: Rscript {0}  

        - name: test google drive
          run: Rscript test_gdrive_update.r ${{secrets.CREDENTIALS}} ${{secrets.STATEFILE_GDRIVE}}
